#elasticsearch配置
spring:
  data:
    elasticsearch:
      cluster-name: es-cluster
      cluster-nodes: 127.0.0.1:9300
  redis:
    port: 6379
    database: 1
    timeout: 15000
    password:
    host: 127.0.0.1
    jedis:
      pool:
        max-idle: 8
        min-idle: 2
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456

server:
  port: 8012