spring:
  datasource:
    #数据源基本配置
    username: root
    password: 123456
    #driver-class-name: com.mysql.jdbc.Driver  已经被废弃了
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
  jpa:
    hibernate:
      #更新或者创建数据表结构
      ddl-auto: update
    #控制台显示sql
    show-sql: true

server:
  port: 9000
  servlet:
    context-path: /mall